In [1]:
import csv
import pandas as pd

In [3]:
blabla = pd.read_csv('./1121_043024001_物理學史與人類文明 成績-20230924_1844-comma_separated.csv', sep=',')

In [9]:
blabla

    名字 姓氏         學號  機構    科系                 電子郵件信箱 課程總分 (實得分數)  從這一課程的最後下載
0   廷威  余  110209048 NaN   民族三  110209048@nccu.edu.tw           -  1695581085
1   重岳  余  109204019 NaN   社會四  109204019@nccu.edu.tw           -  1695581085
2   冠昕  劉  112306060 NaN  資管一乙  112306060@nccu.edu.tw           -  1695581085
3   宗軒  劉  111306072 NaN  資管二乙  111306072@nccu.edu.tw           -  1695581085
4   昭邑  劉  111102014 NaN   教育二  111102014@nccu.edu.tw           -  1695581085
..  .. ..        ...  ..   ...                    ...         ...         ...
68  采纓  駱  109102056 NaN   教育四  109102056@nccu.edu.tw           -  1695581085
69  柏誠  黃  112703033 NaN   資訊一  112703033@nccu.edu.tw           -  1695581085
70  楨淇  黃  112208008 NaN  經濟一乙  112208008@nccu.edu.tw           -  1695581085
71  永豪  黃  108504001 NaN  斯語四甲  108504001@nccu.edu.tw           -  1695581085
72  婕瑄  龔  112306086 NaN  資管一乙  112306086@nccu.edu.tw           -  1695581085

[73 rows x 8 columns]

In [24]:
formated = blabla.drop(columns=['機構', '課程總分 (實得分數)', '從這一課程的最後下載'])
formated["姓名"] = formated['姓氏'] + formated['名字']
formated = formated.drop(columns=['姓氏', '名字'])
formated = formated.reindex(columns=['科系', '學號', '姓名', '電子郵件信箱'])
formated = formated.sort_values(by=['科系'])
formated

      科系         學號    姓名                 電子郵件信箱
31  中文四乙  109101102    江灝  109101102@nccu.edu.tw
40  企管三甲  110305007   王采逸  110305007@nccu.edu.tw
54  企管二乙  111305030   邱梓倩  111305030@nccu.edu.tw
33  傳院二乙  111405026   沈子鑑  111405026@nccu.edu.tw
38  傳院二甲  111405197   王安睿  111405197@nccu.edu.tw
..   ...        ...   ...                    ...
39   阿文四  109502013   王彤家  109502013@nccu.edu.tw
5    韓文三  109507017   劉芷妤  109507017@nccu.edu.tw
6    韓文四  109507006   古孟庭  109507006@nccu.edu.tw
11   風管一  112308017  嚴吳宗祐  112308017@nccu.edu.tw
59   風管二  111308045   陳令承  111308045@nccu.edu.tw

[73 rows x 4 columns]

In [25]:
formated.to_excel('./1121_043024001_物理學史與人類文明 成績-20230924_1844.xlsx')

In [27]:
import datetime
now = datetime.datetime.now()

In [31]:
now.strftime("%Y-%m-%d_%H:%M:%S")

'2023-09-25_03:21:26'